spring:
  datasource:
    url: jdbc:h2:mem:testdb # Using an in-memory H2 database
    username: sa
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # You can use 'update' or 'create-drop' for development, 'none' for production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true # Set to true for debugging SQL queries (optional)
        format_sql: true # Set to true for formatted SQL queries (optional)

server:
  port: 8080 # Set your desired server port
