spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/budget-buddy
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:database/schema.sql